controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder_plate_rotate_joint
      - shoulder_lift_joint
      - elbow_flex_joint
      - wrist_flex_joint
      - wrist_pan_joint
  - name: fake_gripper_controller
    joints:
      - gripper_left_joint